In [2]:
from numpy import *

In [3]:
a = array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = array([2,3,4,5])

In [6]:
a+b

array([3, 5, 7, 9])

In [7]:
c= a+b

In [8]:
c

array([3, 5, 7, 9])

In [9]:
d = a* b

In [10]:
d

array([ 2,  6, 12, 20])

In [11]:
a

array([1, 2, 3, 4])

In [12]:
b

array([2, 3, 4, 5])

In [17]:
import matplotlib

In [19]:
sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [21]:
plot(sin(a))